platform :ios, '13.0'
use_frameworks!

target 'App' do
  pod 'CombineExt'
  pod 'Solar'
  pod 'Interpolate'
  pod 'TinyConstraints'
  pod 'PinLayout'
  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'MarqueeLabel'
  pod 'FlexLayout'
  pod 'CombineCocoa'
  pod 'Kingfisher', '~> 7.6.2'
  pod 'CocoaSecurity'
  pod 'AloeStackView'
  pod 'RxGesture'
  pod 'SwiftReorder'
  pod 'SwiftSimplify'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReactorKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
    end
  end
end
